version: '3.8'

volumes:
  server_node_modules:
  web_node_modules:

services:
  server:
    container_name: server
    restart: always
    build: ./server
    command: sh -c "npm run start"
    ports:
      - '3000:3000'
    volumes:
      - ./server/:/app/
      - server_node_modules:/app/node_modules
    networks:
      - dashboard

  web:
    container_name: web
    restart: always
    build: ./web
    command: sh -c "npm run dev"
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./web/:/app
      - web_node_modules:/app/node_modules
    networks:
      - dashboard

networks:
  dashboard:
    driver: bridge
